apiVersion: batch/v1
kind: CronJob
metadata:
  name: print-date
spec:
  schedule: "*/2 * * * *" # Runs every 1 minutes
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: print-date
            image: busybox
            args:
            - /bin/sh
            - -c
            - date
          restartPolicy: OnFailure

