apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  name: adi
spec:
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: hellow-world
        name: adi
        resources: {}
      restartPolicy: Never
status: {}
