apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  name: ubu
spec:
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: ubuntu
        name: ubu
        command:
        - sleep
        - "50"
        resources: {}
      restartPolicy: Never
status: {}

