apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: demo1
  name: demo1
spec:
  ports:
  - name: 9090-9090
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: demo1
  type: NodePort
status:
  loadBalancer: {}
