apiVersion: apps/v1
kind: StatefulSet
metadata:
  creationTimestamp: null
  labels:
    app: demo4
  name: demo4
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: demo4
  serviceName: demo4 
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: demo4
    spec:
      containers:
      - image: adikarthik/demo
        name: demo
        ports:
        - containerPort: 9094
        resources: {}
status: {}
